//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arts.Buzz.Web.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class appuser
    {
        public string userid { get; set; }
        public Nullable<byte> defaultlang { get; set; }
        public string password { get; set; }
        public string nickname { get; set; }
        public Nullable<byte> voicelang { get; set; }
        public string email { get; set; }
    }
}
