//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arts.Buzz.Web.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class appversion
    {
        public int id { get; set; }
        public string version { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public string url_server { get; set; }
        public System.Guid publishedversion { get; set; }
    }
}
