//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arts.Buzz.Web.Service
{
    using System;
    using System.Collections.Generic;

    public partial class beacon
    {
        public string beaconid { get; set; }
        public string displayname { get; set; }
        public Nullable<int> major { get; set; }
        public Nullable<int> minor { get; set; }
        public Nullable<byte> priority { get; set; }
        public Nullable<int> effectiverangein { get; set; }
        public Nullable<int> effectiverangeout { get; set; }
        public Nullable<int> throughrange { get; set; }
        public Nullable<int> effectiverangein_back { get; set; }
        public Nullable<int> effectiverangeout_back { get; set; }
        public Nullable<int> throughrange_back { get; set; }
        public string usage { get; set; }
        public string rangedirection { get; set; }
    }
}
