//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arts.Buzz.Web.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class beacondb_testEntities : DbContext
    {
        public beacondb_testEntities()
            : base("name=beacondb_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<appuser> appuser { get; set; }
        public DbSet<beacon> beacon { get; set; }
        public DbSet<beaconaction> beaconaction { get; set; }
        public DbSet<beaconuuid> beaconuuid { get; set; }
        public DbSet<content> content { get; set; }
        public DbSet<exbeacon> exbeacon { get; set; }
        public DbSet<excontent> excontent { get; set; }
        public DbSet<exmaster> exmaster { get; set; }
        public DbSet<orgmaster> orgmaster { get; set; }
        public DbSet<syslog> syslog { get; set; }
        public DbSet<sysparams> sysparams { get; set; }
        public DbSet<sysrole> sysrole { get; set; }
        public DbSet<sysuser> sysuser { get; set; }
        public DbSet<trigger> trigger { get; set; }
        public DbSet<userrole> userrole { get; set; }
        public DbSet<appversion> appversion { get; set; }
        public DbSet<sysconfig> sysconfig { get; set; }
    }
}
