//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arts.Buzz.Web.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class content
    {
        public Nullable<byte> contenttype { get; set; }
        public string serverpath { get; set; }
        public string clientpath { get; set; }
        public string filename { get; set; }
        public string description_cn { get; set; }
        public string description_en { get; set; }
        public string description_tw { get; set; }
        public string description_pt { get; set; }
        public string title_cn { get; set; }
        public string title_en { get; set; }
        public string title_tw { get; set; }
        public string title_pt { get; set; }
        public string artist_cn { get; set; }
        public string artist_en { get; set; }
        public string artist_tw { get; set; }
        public string artist_pt { get; set; }
        public Nullable<short> year { get; set; }
        public string contentid { get; set; }
        public byte range { get; set; }
    }
}
