//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arts.Buzz.Web.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class syslog
    {
        public string userid { get; set; }
        public string beaconid { get; set; }
        public Nullable<System.DateTime> logtime { get; set; }
        public Nullable<byte> triggertype { get; set; }
        public long id { get; set; }
        public string extag { get; set; }
    }
}
